name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ">=6.5.0 <8.0.0"
  build: ^2.4.1
  dart_style: ^2.0.1
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 4.0.0-dev.14
  path: ^1.8.1
  source_gen: ^2.0.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.2.0
  matcher: ^0.12.12
  test: ^any
  very_good_analysis: ^5.0.0+1
